# Generated by Django 2.2.3 on 2019-07-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Study', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
